Collections
NiklavsKalvans/c-sharp-syllabus pull request #7
Opened 2021-08-12 11:18 UTC by NiklavsKalvans

Collections pull request.

2021-08-12 19:42 UTC, ausmoons requested changes

2021-08-12 19:42 UTC, ausmoons commented on csharp-basics/exercises/Collections/FlightPlanner/Program.cs
> +                        }
} nav parezi novietotas.  Jābūt tā pat kā zem else, while vai switch

2021-08-12 19:42 UTC, ausmoons commented on csharp-basics/exercises/Collections/FlightPlanner/Program.cs
> +                            Console.WriteLine($"You are at {cities[3]}. You can go to {citiesAndDestinations[cities[3]]} now!(2/6)");
Šo daļu tu atkārto vairākas reizes. Varēji iznest metodi, kur padod int

2021-08-23 15:39 UTC, EdgarsSalmins approved these changes

2021-08-23 16:44 UTC, ausmoons approved these changes

2021-08-24 04:30 UTC, merged